import { slugToUrl } from '@/lib/slug';
import type { Metadata } from 'next';
import Link from 'next/link';

function tryDecode(slug: string): string | null {
  try {
    const decoded = slugToUrl(slug);
    const u = new URL(decoded);
    if (u.protocol !== 'https:') return null;
    return u.toString();
  } catch {
    return null;
  }
}

export async function generateMetadata({ params }: { params: { slug: string } }): Promise<Metadata> {
  const target = tryDecode(params.slug);
  const title = target ? `Link to ${new URL(target).host}` : 'Backlink';
  const description = target ? `Resource directory entry linking to ${target}` : 'Invalid backlink';
  return {
    title,
    description,
    alternates: target ? { canonical: target } : undefined,
    robots: { index: true, follow: true },
    openGraph: target ? { title, description, url: target } : undefined,
    twitter: target ? { card: 'summary', title, description } : undefined,
  };
}

export default function BacklinkPage({ params }: { params: { slug: string } }) {
  const target = tryDecode(params.slug);
  if (!target) {
    return (
      <div className="card">
        <h1>Backlink not found</h1>
        <p>Invalid link slug.</p>
      </div>
    );
  }
  const u = new URL(target);
  const anchors: string[] = [
    `Visit ${u.host}`,
    `Learn more at ${u.host}`,
    `${u.host} official site`,
  ];

  return (
    <article className="card" style={{ lineHeight: 1.6 }}>
      <h1 style={{ marginTop: 0 }}>Resource: {u.host}</h1>
      <p>
        Explore <a href={target} rel="nofollow noopener" target="_blank">{u.hostname}</a> for information, guides, and services.
      </p>
      <ul>
        {anchors.map((text, i) => (
          <li key={i}>
            <a href={target} rel="noopener" target="_blank">{text}</a>
          </li>
        ))}
      </ul>
      <p className="small">This directory entry is autogenerated to reference the site above.</p>
      <p className="small">Back to <Link href="/">home</Link>.</p>
    </article>
  );
}
